# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "gke-example-cluster"
    key    = "example-2.gkecluster.com/k8s/terraform.tfstate"
    region = "eu-west-1"
  }
}
